# Config file for automatic testing at travis-ci.org

language: python
python:
    - 3.6
# Can't test python 3.7 or 3.8 because it will conflict with the python required for ISIS.
# Maybe changing Travis to a conda install of ISIS, and then a tox build would work?  Not sure.
env:
    - ISISVER=3.6.1 CONDANAME=isis3 VARINIT=isis3VarInit.py
    - ISISVER=3.8.1 CONDANAME=isis3 VARINIT=isis3VarInit.py
    - ISISVER=3.9.0 CONDANAME=isis3 VARINIT=isis3VarInit.py
    - ISISVER=4.0.0 CONDANAME=isis VARINIT=isis3VarInit.py
    - ISISVER=4.1.0 CONDANAME=isis VARINIT=isis3VarInit.py
# env: ISISVER=4.2.0 CONDANAME=isis VARINIT=isis3VarInit.py  <-- having an error on Travis with libarmadillo, skipping
# env: ISISVER=4.3.0 CONDANAME=isis VARINIT=isisVarInit.py  <-- not released



# Here we install Miniconda:
before_install:
    - sudo apt-get update
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda config --add channels conda-forge
    - conda config --add channels usgs-astrogeology
    - conda config --show channels

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    # Install and activate ISIS:
    - conda create -q -n test python=$TRAVIS_PYTHON_VERSION
    - conda install -q -n test -c usgs-astrogeology $CONDANAME=$ISISVER
    - source activate test
    - python $CONDA_PREFIX/scripts/$VARINIT --data-dir="$TRAVIS_BUILD_DIR/test-ISIS3DATA"
    - source activate test
    - conda info -a
    - python --version
    #- pip install -U tox-travis
    - pip install -U flake8

before_script: make -B test-resources

# Command to run tests, e.g. python setup.py test
script:
    - flake8 kalasiris tests
    - python setup.py test


# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: rbeyer
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: rbeyer/kalasiris
#     python: 3.6
