# This workflow is purely to determine code coverage.
# Since there were issues with the pinned version of older versions of ISIS
# and we really only need to run coverage once (not N times for every combination
# in a test matrix), there is some duplication with the primary testing workflow.

name: Code Coverage

on: [push, pull_request]

env:
  python-version: 3.6.1

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Conda setup
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ env.python-version }}
        channels: usgs-astrogeology, conda-forge
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install ISIS
      run: |
        conda install -q -y -c usgs-astrogeology isis=4.3.0
    - name: ISIS varinit
      run: |
        python $CONDA_PREFIX/scripts/isisVarInit.py --data-dir="$GITHUB_WORKSPACE/test-ISISDATA"
    - name: Test Install
      run: python -m pip install -e .
    - name: Test with pytest and generate coverage report
      run: |
        conda install pytest
        conda install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
